--  Basic
require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")

-- Plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.mason")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.null-ls")
require("plugins.nvim-comment")
require("plugins.dashboard")
require("plugins.gitstatus")
require("plugins.todo")
require("plugins.colors")
require("plugins.telescopeFileBrouser")
require("plugins.pr-fold")
